import {
  ImgRefillLitecoin,
  ImgRefillEthereum,
  ImgRefillTinkoff,
  ImgRefillMegafon,
  ImgRefillBitcoin,
  ImgRefillAdvCash,
  ImgRefillBilajn,
  ImgRefillTele2,
  ImgRefillApple,
  ImgRefillSber,
  ImgRefillQiwi,
  ImgRefillLolz,
  ImgRefillGpay,
  ImgRefillAlfa,
  ImgRefillMts,
  ImgRefillPM,
} from "../assets";

export const refillImagesConfig = [
  {
    // class: "w-[43px] h-[18px] ",
    src: ImgRefillGpay,
    alt: "Google pay",
    height: 18,
    width: 43,
    class: "",
  },
  {
    // class: "w-[30px] ",
    src: ImgRefillTinkoff,
    alt: "Tinkoff",
    height: 30,
    width: 25,
    class: "",
  },
  {
    // class: "w-[45px] h-[20px] ",
    src: ImgRefillTele2,
    alt: "Tele2",
    height: 38,
    width: 91,
    class: "",
  },
  {
    // class: "w-[40px] h-[20px] ",
    alt: "Perfect money",
    src: ImgRefillPM,
    height: 39,
    width: 80,
    class: "",
  },
  {
    // class: "w-[52px] h-[12px] ",
    src: ImgRefillBilajn,
    alt: "Билайн",
    width: 107,
    height: 24,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillMegafon,
    alt: "Мегафон",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillLitecoin,
    alt: "Litecoin",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[40px] ",
    src: ImgRefillEthereum,
    alt: "Ethereum",
    height: 57,
    width: 57,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillQiwi,
    alt: "Qiwi",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillApple,
    alt: "Apple",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillSber,
    alt: "Сбер",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[16px] ",
    src: ImgRefillAlfa,
    alt: "Альфа банк",
    height: 50,
    width: 32,
    class: "",
  },
  {
    // class: "",
    src: ImgRefillLolz,
    alt: "Bitcoin2",
    height: 50,
    width: 80,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillMts,
    height: 50,
    alt: "Mts",
    width: 50,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillBitcoin,
    alt: "Bitcoin",
    height: 50,
    width: 50,
    class: "",
  },
  {
    // class: "w-[25px] h-[25px] ",
    src: ImgRefillAdvCash,
    alt: "AdvCash",
    height: 50,
    width: 58,
    class: "",
  },
];
